import "./globals.css";
import { Noto_Sans_Thai_Looped, Sarabun } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const sarabun = Sarabun({
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-sarabun",
  display: "swap",
});

const notoSansThai = Noto_Sans_Thai_Looped({
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-noto-sans-thai",
  display: "swap",
});

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${notoSansThai.variable} ${notoSansThai.className} ${sarabun.variable} ${sarabun.className} antialiased`}>
				<TooltipProvider>
					{children}
				</TooltipProvider>
			</body>
		</html>
	);
}
