import "./globals.css";
import { Noto_Serif_Thai } from "next/font/google";
import { TooltipProvider } from "@/components/ui/tooltip";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const notoSerifThai = Noto_Serif_Thai({
  subsets: ["thai", "latin"],
  weight: "variable",
  variable: "--font-noto-serif-thai",
  display: "swap",
});

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${notoSerifThai.variable} ${notoSerifThai.className} antialiased`}>
				<TooltipProvider>
					{children}
				</TooltipProvider>
			</body>
		</html>
	);
}
